### ISSUE TITLE
PSP memory, port, and EEPROM functions assume direct-mapped access

### ISSUE THREAD

**Issue by skliper** [nasa/PSP#10]
The PSP currently provides a number of access functions such as CFE_PSP_MemWrite8/16/32, CFE_PSP_PortRead8/16/32, etc.

These functions all assume that the memory is directly accessible to the current process by simply casting the address as a pointer and directly reading/writing from it.  Unfortunately this is often ***NOT*** the case.
* I/O port access in the x86/intel world is never memory mapped and requires different instructions (inline asm or kernel syscalls) in order to get to it.
* When using virtual memory, physical memory addresses are not directly accessible to the running process until the memory is mapped into the current virtual memory space.
* Many EEPROM devices are actually connected via a serial bus such as SPI or TWI and therefore would not be memory mapped.

With the way it is structured right now, cfe_psp_ram.c, cfe_psp_port.c, and (to a lesser degree) cfe_psp_eeprom.c only provide slow performance-robbing function calls to simply cast a pointer.

Furthermore, it is arguable whether direct I/O port or physical memory access even belongs in the PSP at all; the API this provides to the application layer remains far too hardware-specific to provide any useful abstraction.  Any CFS application performing direct I/O is already unlikely to be portable to any other platform, since (by definition) this would be accessing a specific hardware device at a specific location.

Proposed changes:
* Stop compiling cfe_psp_ram.c, cfe_psp_port.c, and cfe_psp_eeprom.c from the "shared" code by default; what these currently implement is more of an exception than the general rule.  These can be renamed or moved to indicate they are not always used.
* Deprecate/discourage future use of the RAM/port access functions.  Instead, a "driver" architecture should be used so the hardware device can be better abstracted (see #6   This also allows easier simulation of the hardware, and the resulting CFS application will be much more portable/reusable.
* On the PSP's for which direct memory access //is// valid, they can continue to compile-in the current implementations to maintain backward compatibility.
* On the PSP's for which direct memory access //is not// valid, either customized functions can be provided or simply return the NOT_IMPLEMENTED error.

**Comment by skliper** [comment]
@jphickey is this a candidate for config/source selection related updates?  I didn't refresh on all the comments, but separate the code and select source files as needed.

**Comment by jphickey** [comment]
Yes - to clarify this would be a prime example for the fully-modular PSP concept.  With the pending merge that moves the startup code to OSAL BSP, this becomes more possible where a "PSP name" is just a collection of modular code abstraction blobs for that platform.  I'd like to see all remaining PSP functions, including these, go in that direction.
