### ISSUE TITLE
recommended lgtm issues:

### ISSUE THREAD

**Issue by avan989** [nasa/PSP#126]
**Is your feature request related to a problem? Please describe.**
Recommended issue from lgtm:

cfe_psp_module.h
```
typedef enum
--
37 | {
  | In an enumerator list, the = construct should not be used to explicitly initialize members other than the first, unless all items are explicitly initialized.
38 | CFE_PSP_MODULE_TYPE_INVALID = 0,
39 | CFE_PSP_MODULE_TYPE_VALID_RANGE  = 1000,
```

**Comment by skliper** [comment]
Definitely worth clarifying.

https://github.com/nasa/PSP/blob/502e83ae179f0c439d6cddf310eede319eb44711/fsw/shared/cfe_psp_module.h#L36-L43

Should be understandable at a quick glance.  @jphickey any suggestions?  Not clear to me what the intent is here.

**Comment by jphickey** [comment]
It is simply intended to provide unique(-ish) numeric values for the valid enumerators.  If every enumeration in the system starts with 1, then it is easy to interchange.  Using a starting value other than 1 offers a modicum of protection against using incorrect values (i.e. if someone passed a pointer to the wrong struct, or something).

I'm not sure why this is an lgtm "issue" as it is pretty well defined in the C standard how enum declarations work.  But if you'd rather start with 1, it won't change the behavior, but it will make it a little _less_ secure.
