### ISSUE TITLE
C++ comment style and commented out code violations

### ISSUE THREAD

**Issue by skliper** [nasa/PSP#246]
**Is your feature request related to a problem? Please describe.**
C++ comment style and commented out code violates style guidelines
https://github.com/nasa/PSP/blob/0cd14abbb58691eb83afdd816e116f68e681b8e0/fsw/pc-rtems/src/cfe_psp_memory.c#L544-L565

**Describe the solution you'd like**
Clean up

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by skliper** [comment]
Need to figure out if these should be actually implemented or removed.

**Comment by zanzaben** [comment]
The parts commented out have been that way since it was first brought over from the PSP 1.3.0.0 code base 2 years ago so I am confident it can be removed. 

Also the function CFE_PSP_MemReport isn't used anywhere else in the code base so should it be removed entirely.

**Comment by astrogeco** [comment]
[CCB:2021-02-24](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-February-24-2021) APPROVED
- Remove, probably an old debug function

**Comment by skliper** [comment]
CCB 20210224 - votes to remove function/file
