### ISSUE TITLE
Enable "format check" workflow for push to all branches

### ISSUE THREAD

**Issue by astrogeco** [nasa/PSP#297]
**Is your feature request related to a problem? Please describe.**
The format check workflow only runs for pull requests or for pushes to "main" so it will not run on work done in forks. 

**Describe the solution you'd like**
Remove branch restriction for "push" trigger and add "check for duplicates" job

**Describe alternatives you've considered**
None

**Comment by skliper** [comment]
#317 switched to use the shared workflow, so this is no longer applicable.

https://github.com/nasa/PSP/blob/a260e9cc0a8fa5c96e55b1df4d39a6799a812ea4/.github/workflows/format-check.yml#L1-L11
