### ISSUE TITLE
Add EEPROM read and block read/write APIs

### ISSUE THREAD

**Issue by skliper** [nasa/PSP#335]
**Is your feature request related to a problem? Please describe.**
No PSP API's for EEPROM write block, or any EEPROM reads.

**Describe the solution you'd like**
Add CFE_PSP_EepromWriteBlock, Read[8|16|32|Block]

**Describe alternatives you've considered**
None

**Additional context**
#274 
This would better support MM EEPROM actions with specific APIs for reading writing vs the former use of the generic CFE_PSP_MemCpy, CFE_PSP_MemSet.  Could consider deprecating all the ram API's since they aren't really useful, the calls are surrounded w/ validity checks already so not really clear why they are necessary.

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by astrogeco** [comment]
[CCB:2022-04-13](https://github.com/nasa/cFS/wiki/CCB:-2022.04.13) Closing
- Path forward is to deprecating these functions and have MM work with RAM
- We'll need to update some requirements in MM
- PSP proper isn't the right place for this functionality
