### ISSUE TITLE
Use (foo), not &(foo[0]), where appropriate

### ISSUE THREAD

**Issue by skliper** [nasa/PSP#66]
In a number of places, code jumps through extra hoops
to take the address of the first element of an array,
rather than just allowing the array name to gracefully
decay into the pointer.

Where just using the array name is more correct, we should
simplify the code to use it.

**Comment by skliper** [comment]
_Imported from trac issue 62.  Created by glimes on 2016-04-19T13:16:13, last modified: 2019-08-14T14:13:14_

**Comment by skliper** [comment]
_Trac comment by jhageman on 2019-07-08 09:45:22:_

Moved tickets that aren't ready for end of summer (2019) release to 1.4.1

**Comment by skliper** [comment]
_Trac comment by jhageman on 2019-08-13 10:39:45:_

Did grep -r "[0])", "])" and "] )" just to catch most syntax, only cases were in fsw/mcp750-vxworks6.4/cfe_psp_memory.c:

{{{
*PtrToResetArea = (cpuaddr)&(CFE_PSP_ReservedMemoryPtr->ResetMemory[0]);
*PtrToUserArea = (cpuaddr)&(CFE_PSP_ReservedMemoryPtr->UserReservedMemory[0]);
*PtrToVolDisk = (cpuaddr)&(CFE_PSP_ReservedMemoryPtr->VolatileDiskMemory[0]);
}}}

Trivial fix...

**Comment by zufishanali** [comment]
Hi @skliper, may I go ahead and make this change?

**Comment by skliper** [comment]
@zufishanali Please do!  Note we are still trying to get the contribution process/documentation finalized with our legal office so it may take a while to merge (and there will likely be a form to sign), but any/all contributions are encouraged!  Likely you'll need to grep again to identify any current cases.
